islandora_iiif.settings:
  type: config_object
  label: 'Islandora IIIF Settings'
  mapping:
    iiif_server:
      type: string
      label: 'IIIF Server Url'
    use_relative_paths:
      type: boolean
      label: 'Use relative paths in manifest.'
    show_title:
      type: string
      label: 'Show title in view'

views.style.iiif_manifest:
  type: views_style
  mapping:
    iiif_tile_field:
      type: sequence
      label: "Tile source field(s)"
      sequence:
        type: string
    iiif_ocr_file_field:
      type: sequence
      label: "Structured OCR data file field"
      sequence:
        type: string
    structured_text_term_uri:
      type: string
      label: "Structured text term"
    search_endpoint:
      type: string
      label: "Search endpoint path"
